name: Build, Test And Deploy
on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Build
        run: |
          pnpm install
          pnpx playwright install-deps
          pnpx playwright install
          pnpm run build:prod
      - name: Run build & tests (Testing)
        run: |
          pnpm run build
          pnpm run test:units
        env:
          TEST_WEBKIT: 1
      - name: Run conformance tests (Testing)
        run: pnpm run test:conformance
      - name: Run build & tests (Production)
        run: |
          pnpm run build:prod
          pnpm run test:units
        env:
          TEST_WEBKIT: 1
      - name: Run conformance tests (Production)
        run: pnpm run test:conformance
      - name: Run benchmark
        run: pnpm run benchmark
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./packages/core/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: ./packages/core/dist
      - uses: ncipollo/release-action@v1
      - name: Publish package on NPM
        run: |
          npm run prepare:publish
          cd ./packages/core
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PBW_MOON }}